baseURL = "https://moyanzhu01.github.io/"
languageCode = "en"
title = "Moyan Zhu"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false

[params]
  defaultTheme = "auto"
  description = "Ph.D. Candidate in Finance"
  
  [params.homeInfoParams]
    Title = "Hi, I'm Moyan Zhu ğŸ‘‹"
    Content = """
    Ph.D. Candidate in Finance at University of International Business and Economics.
    
    Focusing on Empirical Asset Pricing, and Market Micro-structure.
    """
    imageUrl = "img/avatar.png"     # è¿™é‡Œå¡«ä½ åˆšæ‰æ‹–è¿›å»çš„å¤´åƒæ–‡ä»¶å
    imageLayout = "same"            # å›¾ç‰‡å±…ä¸­ (å¯é€‰: "profile" å¹¶æ’æ˜¾ç¤º, "same" æˆ–å…¶ä»–å€¼å±…ä¸­æ˜¾ç¤º)
    imageWidth = 300                # å›¾ç‰‡å®½åº¦ï¼ˆåƒç´ ï¼‰ï¼Œé»˜è®¤ 150
    imageHeight = 400               # å›¾ç‰‡é«˜åº¦ï¼ˆåƒç´ ï¼‰ï¼Œé»˜è®¤ 150

[params.label]
text = "Moyan Zhu"      # ç½‘ç«™å·¦ä¸Šè§’æ˜¾ç¤ºçš„æ–‡å­—ï¼ˆé€šå¸¸å†™ä½ çš„åå­—ï¼‰

  [params.assets]
    # æµè§ˆå™¨æ ‡ç­¾é¡µå›¾æ ‡ï¼ˆFaviconï¼‰
    favicon = "img/favicon.png"              # é»˜è®¤å›¾æ ‡ï¼ˆå¯ä»¥æ˜¯ .ico æˆ– .pngï¼‰
    favicon16x16 = "img/favicon.png"          # 16x16 åƒç´ å›¾æ ‡
    favicon32x32 = "img/favicon.png"          # 32x32 åƒç´ å›¾æ ‡
    apple_touch_icon = "img/favicon.png"      # Apple è®¾å¤‡å›¾æ ‡ï¼ˆå»ºè®® 180x180ï¼‰
    safari_pinned_tab = "img/favicon.png"     # Safari å›ºå®šæ ‡ç­¾é¡µå›¾æ ‡ï¼ˆSVG æ ¼å¼ï¼‰
    theme_color = "#2e2e33"                # ä¸»é¢˜é¢œè‰²ï¼ˆæµè§ˆå™¨åœ°å€æ é¢œè‰²ï¼‰
    msapplication_TileColor = "#2e2e33"   # Windows ç£è´´é¢œè‰²

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10

[[menu.main]]
  identifier = "research"
  name = "Research"
  url = "/research/"
  weight = 20

[[menu.main]]
  identifier = "posts"
  name = "Blog"
  url = "/posts/"
  weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true